DROP TABLE ERS_REIMBURSEMENT;
DROP TABLE ERS_USERS;
TRUNCATE ERS_REIMBURSEMENT ;





INSERT INTO  ERS_USERS_Role(USER_ROLE)
VALUES ('manager');

CREATE TABLE ERS_USERS(
	ERS_USERS_ID SERIAL PRIMARY KEY,
	ERS_USERNAME VARCHAR(50) UNIQUE NOT NULL,
	ERS_PASSWORD VARCHAR(50) NOT NULL,
	USER_FIRST_NAME VARCHAR(100) NOT NULL,
	USER_LAST_NAME VARCHAR(100) NOT NULL,
	USER_EMAIL VARCHAR(100) UNIQUE NOT NULL,
	USER_ROLE_ID INTEGER NOT NULL,
	CONSTRAINT fk_ERS_USERS_ROLE
		FOREIGN KEY (USER_ROLE_ID)
			REFERENCES ERS_USERS_ROLE(ERS_USER_ROLE_ID)	
);


CREATE TABLE ERS_USERS_ROLE(
	ERS_USER_ROLE_ID SERIAL PRIMARY KEY,
	USER_ROLE VARCHAR(10) NOT NULL
);

CREATE TABLE ERS_REIMBURSEMENT(
	REIMB_ID SERIAL PRIMARY KEY,
	REIMB_AMOUNT REAL NOT NULL,
	REIMB_SUBMITTED TIMESTAMP NOT NULL,
	REIMB_RESOLVED TIMESTAMP,
	REIMB_DESCRIPTION VARCHAR(250),
	--REIMB_RECEIPT bytea,
	REIMB_AUTHOR INTEGER NOT NULL,
	REIMB_RESOLVER INTEGER,
	REIMB_STATUS_ID INTEGER NOT NULL,
	REIMB_TYPE_ID INTEGER NOT NULL,
	CONSTRAINT fk_ERS_USERS
		FOREIGN KEY (REIMB_AUTHOR) REFERENCES ERS_USERS(ERS_USERS_ID),
		FOREIGN KEY (REIMB_RESOLVER) REFERENCES ERS_USERS(ERS_USERS_ID),
	CONSTRAINT fk_ERS_REIMBURSEMENT_STATUS
		FOREIGN key(REIMB_STATUS_ID) REFERENCES ERS_REIMBURSEMENT_STATUS(REIMB_STATUS_ID),
	CONSTRAINT fk_ERS_REIMBURSEMENT_TYPE
		FOREIGN key(REIMB_TYPE_ID) REFERENCES ERS_REIMBURSEMENT_TYPE(REIMB_TYPE_ID)		
);

CREATE TABLE ERS_REIMBURSEMENT_TYPE(
	REIMB_TYPE_ID SERIAL PRIMARY KEY,
	REIMB_TYPE VARCHAR(10) NOT NULL
);

CREATE TABLE ERS_REIMBURSEMENT_STATUS(
	REIMB_STATUS_ID SERIAL PRIMARY KEY,
	REIMB_STATUS VARCHAR(10) NOT NULL 
);

ALTER TABLE ERS_USERS ALTER COLUMN ERS_PASSWORD TYPE Varchar(65);

-- INSERT into ERS_REIMBURSEMENT_TYPE's
--INSERT INTO  ERS_REIMBURSEMENT_TYPE(REIMB_Type)
--VALUES ('LODGING');
--INSERT INTO  ERS_REIMBURSEMENT_TYPE(REIMB_Type)
--VALUES ('TRAVEL');
--INSERT INTO  ERS_REIMBURSEMENT_TYPE(REIMB_Type)
--VALUES ('FOOD');
--INSERT INTO  ERS_REIMBURSEMENT_TYPE(REIMB_Type)
--VALUES ('OTHER');
--- Insert into  ERS_REIMBURSEMENT_STATUS 
--INSERT INTO  ERS_REIMBURSEMENT_STATUS(REIMB_STATUS)
--VALUES ('pending'),('approved'),('denied');
-- temp user need to encrypt password so for testing nothing else
--INSERT INTO  ERS_USERS(ERS_USERNAME,ERS_PASSWORD,USER_FIRST_NAME,USER_LAST_NAME,USER_EMAIL,USER_ROLE_ID)
--VALUES ('billy@toledo','password','billy','toledo','billy@gmail.com', 1);
--INSERT INTO  ERS_USERS(ERS_USERNAME,ERS_PASSWORD,USER_FIRST_NAME,USER_LAST_NAME,USER_EMAIL,USER_ROLE_ID)
--VALUES ('manager','password','william','smith','smith@gmail.com', 2);

-- testing reimbursement request
INSERT INTO  ERS_REIMBURSEMENT(Reimb_amount,REIMB_SUBMITTED,REIMB_DESCRIPTION,REIMB_AUTHOR,REIMB_STATUS_ID,REIMB_TYPE_ID)
VALUES (200,CURRENT_TIMESTAMP,'Plane ticket',2,1,2)
-- This only update if it exist already 
UPDATE ERS_REIMBURSEMENT
SET REIMB_RESOLVER = 3, 
REIMB_RESOLVED = CURRENT_TIMESTAMP,
REIMB_STATUS_ID = 3
WHERE REIMB_STATUS_ID = 1 AND REIMB_ID = 6;


UPDATE ERS_USERS 
SET ERS_PASSWORD = '$2a$12$ZqNef9v/mfaDxal74y7aAOI3JDn99hTBFXpNVZ2wAOBYS/nwFTOg2'
WHERE ERS_USERS_ID  = 4;



INSERT INTO  ERS_USERS(ERS_USERNAME,ERS_PASSWORD,USER_FIRST_NAME,USER_LAST_NAME,USER_EMAIL,USER_ROLE_ID)
VALUES ('pilot','$2a$12$XU8kCHu4Nf4FwRKO7lkWXOhUyc7Gu1t21weOP6oaC8HLrEMZkTbsW','Leela','Turanga','leela@express.com', 2);


